symfony-cmf/Testing

- resources/web/app_test.php
- src/HttpKernel/TestKernel.php
- tests/HttpKernel/TestKernelTest.php
- Do not change the default error reporting level
- And fix call to deprecated Kernel::init
> Do not override error reporting configuration

- bin/travis/phpcr_odm_doctrine_dbal.sh
The init command now requires `--force` as of https://github.com/jackalope/jackalope-doctrine-dbal/pull/232
> Added force option to init command

- bootstrap/bootstrap.php
- src/ErrorHandler/DeprecationErrorHandler.php
This was done in Symfony to replace the long deprecated errors in the Travis tests with a short summary at the end of the tests.
@nicolas-grekas are you ok with this? I'm happy to remove it if you don't agree (we'll remove it anyway if you create a component)
> Copied deprecation error handler from core

- src/HttpKernel/TestKernel.php
TreeBrowserBundle 2.0 does not use FOSJsRoutingBundle anymore
> Optionally include FOSJsRoutingBundle

- .travis.yml
- composer.json
- src/HttpKernel/TestKernel.php
The latest TreeBrowserBundle does no longer install fos js routing bundle. Optionally including this bundle (as done in #103) means tests will fail because we load a not exisiting routing resource file (of FosJsRouting). To support all TreeBrowserBundle/SonataDoctrinePhpcrBundle versions, we have to include this bundle in the sonata bundle sets.
> Fix FosJsRoutingBundle requirement

- bootstrap/bootstrap.php
All annotation loading configuration could be removed, as it's already done by the PHPunit bridge which we rely on now: https://github.com/symfony/phpunit-bridge/blob/2.7/bootstrap.php#L17-19
This also fixes PHP 7 support (as the `String` annotation is lazy loaded after this PR)
> Remove annotation registry loading

- src/Functional/DbManager/PHPCR.php
Currently, initializers were never run as they aren't run by the executor when append = true. The executor already purges the database, so no need to purge it ourselves.
As everything is purged already, appending doesn't make much sense.
ping @dantleech can you please verify these changes as you know much more about the Doctrine stuff than me.
> Let executor purge the database

- resources/config/default.php
- resources/config/dist/framework.php
- resources/config/dist/phpcr_odm.php
- resources/config/doctrine_orm.php
- resources/config/phpcr_odm.php
- resources/config/sonata_admin.php
On second thought, copying all resources to each bundle is not going to be very usefull. Symfony 2.8 comes with a great, flexible alternative to have default config in this bundle while still allowing changing everything in bundles: the `MicroKernel`. This means that for Testing 2.0 (which will be Symfony >2.8), we can switch to that and deprecating them in 1.3 does no longer make sense.
The deprecation notices weren't working at the moment anyway, because they didn't use the `E_USER_DEPRECATED` level.
> Undeprecate resources

- bootstrap/bootstrap.php
The ResourceBundle tests are resolving to the 2.0 branch. This branch still loads the annotations manually.
See: https://github.com/doctrine/phpcr-odm/issues/678#issuecomment-168185652
> Removed annotation file load from bootstrap

- resources/config/dist/doctrine.yml
- resources/config/dist/monolog.yml
this invalid syntax is currently supported by symfony but since 3.3 triggers warnings.
> fix yaml syntax

- src/HttpKernel/TestKernel.php
This PR serves a method to use `config/bundles.php` for own bundles to register.
> load bundles from file

- CHANGELOG.md
- src/DependencyInjection/Compiler/TestContainerPass.php
- src/HttpKernel/TestKernel.php
- tests/HttpKernel/TestKernelTest.php
As mentioned in 
https://github.com/symfony/symfony-docs/issues/8097
This is a nice and easy way to still fetch private services from contaier in i.e. web tests.
> build a test compiler

- src/Functional/BaseTestCase.php
- src/Functional/DbManager/PhpcrDecorator.php
i did not add methods to DoctrinePHPCRBundle for things that are not used in the bundle itself. the createTestNode method is used by cmf bundles, have testing provide a method for this.
> the repositorymanager is not BC with the PHPCR manager

- src/Phpunit/DatabaseTestListener.php
| Branch?       | "master"
| Fixed tickets | https://github.com/sonata-project/SonataDoctrinePhpcrAdminBundle/pull/526
A first argument of `Symfony\Component\Process\Process` can be an array only since Symfony 3.3
But now it is always passes an array from `Symfony\Cmf\Component\Testing\Phpunit\DatabaseTestListener::getProcess`. With this PR `$arguments` is converted from array to a string via old method, removed in Symfony4.0.
I.e. for Symfony < 4.0, `$arguments` will be converted to a string, for Symfony>=4.0 it won't be changed
Also, right now a travis job https://travis-ci.org/sonata-project/SonataDoctrinePhpcrAdminBundle/jobs/395310744 of …
> Do not pass command line as array to Process

- bootstrap/kernel_bootstrap.php
| Branch?       | "master"
| Bug fix?      | no
This PR allows to execute `vendor/symfony-cmf/testing/bin/console` without setting environment variables: `KERNEL_DIR` and `KERNEL_CLASS` will be readed from `phpunit.xml.dist` file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<phpunit>
<php>
<ini name="precision" value="8"/>
<server name="KERNEL_DIR" value="tests/Fixtures/App"/>
<env name="KERNEL_CLASS" value="Sonata\DoctrinePHPCRAdminBundle\Tests\Fixtures\App\Kernel"/>
</php>
</phpunit>
```
If this PR will be accepted, `Makefile` in …
> Read KERNEL_DIR and KERNEL_CLASS from phpunit.xml.dist for bin/console

- src/Functional/BaseTestCase.php
- tests/Fixtures/TestTestCase.php
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no
This change should avoid sharing a kernel for `phpcr` envirionment on an `orm` environment. I really played around with phpunit properties for backup of static properties and i failed. In general several classes - and even the test-case - is cached and backuped. So the `$kernel` stays alive through different processes. And yea, i even tried to separate it into different processes, but that failed also. So …
> avoid using same kernel for orm and phpcr

- phpunit.xml.dist
- src/Functional/BaseTestCase.php
- tests/Functional/BaseTestCaseTest.php
Since symfony/symfony@4f91020 , that ships with 4.3.0, there is a
collision between a private static method in a trait use in an ancestor
class of BaseTestCase and the method in BaseTestCase.
See https://github.com/symfony/symfony/blob/950306adaad8b23725c4efeaf6c570d89e17f164/src/Symfony/Bundle/FrameworkBundle/Test/WebTestAssertionsTrait.php#L189
Closes #192
| Branch?       | 2.1
| Deprecations? | yes
| Fixed tickets | #192
| Doc PR        | n/a
> Avoid name collision with parent method

- composer.json
| Branch?       | "master" 
| Bug fix?      | no
There is no `5.x` branch in [monolog-bundle](https://github.com/symfony/monolog-bundle/releases)
> Require proper monolog-bundle dependency

- composer.json
- resources/web/app.php
| Branch?       | "master" 
| Fixed tickets | -
Currently it will install symfony/debug this component is deprecated and should be replaced with symfony/error-handler. I did make the only call to this component optional. Based on the install debug or error handler the correct component is called.
> Remove symfony debug component as requirement

- CHANGELOG.md
- resources/config/dist/framework.php
| Branch?       | -
| Fixed tickets | -
| Doc PR        | -
The framework.tempating does not longer exist in symfony 5 so we should remove it from the default.php if somebody want to configure it it should be done in its project.
> Remove templating config from default.php

- src/Functional/DbManager/ORM.php
- src/Functional/DbManager/PHPCR.php
we need to remove the typehint, because very old versions of doctrine still have persistence in the commons, and the newest versions no longer have the BC layer.
> make compatible with newer doctrine persistence versions

- CHANGELOG.md
- composer.json
- resources/web/router.php
- src/Functional/BaseTestCase.php
- tests/Fixtures/TestTestCase.php
- tests/Functional/BaseTestCaseTest.php
- tests/bootstrap.php
The FrameworkBundle BaseTestCase introduced `getContainer`, which
collides with the non-static method of the same name provided in this
component.
Make getContainer (and other methods) static to match.
| Branch?       | "master"
| BC breaks?    | yes
| Fixed tickets | -
| Doc PR        | -
> Adjust to Symfony FrameworkBundle changes

- resources/config/default.php
- resources/config/dist/security.php
Follow up of #210 and #211. Some extra config changes found while adding symfony 6 compatibility to `symfony-cmf/routing-bundle`
* Use full config path to avoid loading issues with changes currentDir
* Don't use deprecated `encoders` security config when the password hasher component is available
> Extra config changes needed to ensure compitbility over all symfony versions

- .github/workflows/test-application.yaml
- bootstrap/bootstrap.php
Did run into an issue with Annotationregistry loader in phpcr migration bundle: https://github.com/dantleech/phpcr-migrations-bundle/actions/runs/4430029921/jobs/7771245561
> Call AnnotationRegistry registerLoader only when available
