- resources/config/routing/sonata_routing.yml
- tests/HttpKernel/TestKernelTest.php
- tests/Phpunit/DatabaseTestListenerTest.php
Let's try to remove some deprecation notices
> Pattern has been renamed to Path in Sf 2.2

- bin/travis/doctrine_orm.sh
- bin/travis/phpcr_odm_doctrine_dbal.sh
- src/Phpunit/DatabaseTestListener.php
- tests/Phpunit/DatabaseTestListenerTest.php
> Support Jackalope <1.2 and code clean-up

- composer.json
see https://github.com/symfony-cmf/RoutingBundle/pull/280#issuecomment-105221553
> require at least Jackalope 1.1.0 stable

- composer.json
The LocaleListener in the DoctrinePHPCRBundle requires 1.1.0-RC1
> [WIP] Fix deps

- resources/config/default.php
- resources/config/dist/framework.php
- resources/config/dist/phpcr_odm.php
- resources/config/doctrine_orm.php
- resources/config/phpcr_odm.php
- resources/config/sonata_admin.php
> Deprecate resources

- composer.json
- src/Document/Content.php
- src/Functional/DbManager/ORM.php
- src/HttpKernel/TestKernel.php
- src/Phpunit/DatabaseTestListener.php
i suspect we only introduced those dev, alpha and RC deps during development and could go with stable again. correct?
> stable dependencies

- UPGRADE-2.0.md
Created upgrade information for the stuff mentioned in changelog. Do the advices sound to hard?
> create upgrad file

- bin/make/functional_tests_orm.mk
- bin/make/functional_tests_phpcr.mk
- bin/make/test_installation.mk
- bin/make/unit_tests.mk
- bin/scripts/check_install.sh
- composer.json
- phpunit.xml.dist
Those scripts could be used in a Makefile like proofed in: https://github.com/symfony-cmf/seo-bundle/pull/336
> Testing scripts

- bin/scripts/check_install.sh
We are now able to install different symfony versions from 3.3 up and test installation with them
> add possible symfony version to install

- composer.json
| Bug fix?      | no
| New feature?  | yes
> increase phpcr-bundle version

- .travis.yml
- CHANGELOG.md
- Makefile
- README.md
- bootstrap/kernel_bootstrap.php
- composer.json
- resources/config/dist/parameters.yml
- src/Functional/BaseTestCase.php
- src/HttpKernel/TestKernel.php
- src/Phpunit/DatabaseTestListener.php
- tests/Phpunit/DatabaseTestListenerTest.php
Remove all deprecation warnings and other style stuff in generated files.
> Master dev kit

- composer.json
| Branch?       | "master" for new features/current work
| New feature?  | s/no
| BC breaks?    | not
> use dev version of phpcr-bundle

- composer.json
> Use dev version

- resources/config/dist/phpcr_odm.php
Having the new test app directory structure, we should use the new path for the doctrine mapping.
> set the new Document position on for annotation mapping

- .travis.yml
- composer.json
- src/HttpKernel/TestKernel.php
> start on working with symfony 4.0

- .travis.yml
- README.md
> Fix README

- src/Functional/BaseTestCase.php
- tests/Functional/BaseTestCaseTest.php
use phpcr own repository manager and test dev version of phpcr-bundle
> [WIP] test dev version of phpcr-bundle

- .github/Bug_report.md
- .github/Documentation_issue.md
- .github/Feature_request.md
- .github/Security_issue.md
- .github/Support_question.md
- composer.json
this is the first package we use it. it is directly copied from: https://github.com/symfony/symfony/pull/27155 means it is a from symfony.
> Introduce new Github templates - DevKit updates

- bootstrap/kernel_bootstrap.php
| Branch?       | "master"
| Fixed tickets | #182
With this PR setting `<server name="KERNEL_DIR" ... />` will be optional, it will be used by old apps only for console commands when `<env name="KERNEL_CLASS" ... />` was not set yet
> Make usage KERNEL_DIR in phpunit.xml.dist optional

- .travis.yml
- README.md
- composer.json
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no
> DevKit updates - Introduce php 5.6 again

- src/Functional/BaseTestCase.php
- tests/Functional/BaseTestCaseTest.php
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no
> ensure kernel is available and booted

- src/Functional/BaseTestCase.php
The type hint is string.
| Branch?       | 2.1
| Fixed tickets | n/a
| Doc PR        | n/a
> Always pass a string as third argument

- src/Functional/BaseTestCase.php
The type hint is string.
| Bug fix?      | yes/no
| New feature?  | yes/no
| BC breaks?    | yes/no
| Deprecations? | yes/no
> Always pass a string as third argument (#189)

- CHANGELOG.md
- composer.json
> feature packages moved to require-dev to make sure packages using testing declare their dependencies correctly

- resources/config/default.php
- resources/config/dist/framework.php
- resources/config/dist/parameters.yml
- resources/config/dist/parameters_sf5.yml
- resources/config/dist/phpcr_odm.php
- src/HttpKernel/TestKernel.php
| New feature?  | yes
| Doc PR        |
> Use kernel.project_dir if available to support symfony 5

- src/HttpKernel/TestKernel.php
Fix for a bug introduced in #202
> Add missing return in getKernelDir method

- .github/workflows/test-application.yaml
- composer.json
- src/Functional/BaseTestCase.php
- src/HttpKernel/TestKernel.php
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | yes and no 😄 (see comment below)
I'm not sure if I can make the return typehints like this or if it's a bc-break. This is a testing package and the class should be used as is?
Otherwise I can update the PR to do a class check and only change the return types when using symfony 6
> Allow symfony 6
